
spring:
  datasource:
    url: jdbc:h2:file:./src/main/db/mall
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true

server:
  port: 8080
